### ISSUE TITLE
start code

### ISSUE THREAD

**Issue by sajadmhmzd** [VasiliBaranov/packing-generation#28]
hi guys
I'm beginner in using of this code and i dont have any idea about run this code with "visual studio" in windows7, in fact i dont know start with which files? folder , ...
please someone help me (as a real beginner user ) step by step to run this code for first time!
thanks alot

**Comment by VasiliBaranov** [comment]
Hi Sajad,

you can at first try to run the .exe from the release: https://github.com/VasiliBaranov/packing-generation/releases/tag/v1.0.1.28 (scroll to Assets). So no compilation, visual studio, etc. needed, just run it.

If you really want to compile it, please refer to https://github.com/VasiliBaranov/packing-generation/wiki/Compilation . For working with visual studio, you can google smth like "compile a c++ program in visual studio", here is one of the first links: https://docs.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=msvc-160

Hope this helps!

Best Regards,
Vasili
