### ISSUE TITLE
read the output file

### ISSUE THREAD

**Issue by sajadmhmzd** [VasiliBaranov/packing-generation#31]
Hi, how can i read the output file (.xyzd file)? it seem in binary format and i dont know how read it as a x  y  z coordinate.

**Comment by VasiliBaranov** [comment]
Hi,

It depends on the language you are most comfortable with.

Please see this discussion: https://github.com/VasiliBaranov/packing-generation/issues/16

One option from this link is:
> hexdump -v -e '4 "%f "' -e '"\n"' < packing.xyzd > centers_in_ascii.txt

Someone posted a python code here: https://github.com/VasiliBaranov/packing-generation/issues/30

Just reading the file as it is in python is:

> import numpy as np
> packing = np.fromfile('packing.xyzd').reshape(-1, 4)

Hope this helps!

Best Regards,
Vasili
