### ISSUE TITLE
Remove `packing.nfo` between `-fba` and `-ls` runs?

### ISSUE THREAD

**Issue by sgbaird** [VasiliBaranov/packing-generation#33]
https://colab.research.google.com/drive/1wjF6tuGZa3opIWpXIYiKJtmpqBVSpj1E?usp=sharing

**Comment by sgbaird** [comment]
https://github.com/VasiliBaranov/packing-generation/issues/19

**Comment by sgbaird** [comment]
Seems the answer is yes https://github.com/VasiliBaranov/packing-generation/issues/21#issuecomment-680292332

**Comment by VasiliBaranov** [comment]
Hi @sgbaird, i think you found all the relevant comments! Sorry, i probably still need to update the documentation.. Will do over the Christmas time!

**Comment by VasiliBaranov** [comment]
I've actually just updated the section https://github.com/VasiliBaranov/packing-generation#4-sample-usage , so it shall be much better now. Thanks for noticing!

Best Regards,
Vasili
