### ISSUE TITLE
Suggestions for running multiple simulations independent from each other

### ISSUE THREAD

**Issue by sgbaird** [VasiliBaranov/packing-generation#35]
I'm doing optimization and want to be able to run simulations independent of each other. As a workaround, I'm making separate directories for each simulation and copying the EXE file into the directory.

**Comment by VasiliBaranov** [comment]
Hi @sgbaird ,

i think this answer to another question of yours will help: https://github.com/VasiliBaranov/packing-generation/issues/34#issuecomment-1321236431

So you just start several subprocesses separately, but you don't copy the exe, you just run the same exe in multiple current working directories.

And of course, the program will process multiple packings sequentially if they are in subfolders to the current folder (but you know this based on other questions), and that's probably not what you need.

Hope this helps!

Best Regards,
Vasili

**Comment by sgbaird** [comment]
Realizing now this is a duplicate of #34. Thanks for the answers! Seems like the right way to go.
